#!/bin/python3

import os
from openai import OpenAI
import json
import argparse
import requests


# Gets a response from OpenAI, given the OpenAI client, a prompt, and code
# (OpenAI, str, str) -> str
def get_comment(client, prompt, code):
    chat_completion = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": prompt + text,
            }
        ],
        model="gpt-3.5-turbo",
    )

    return chat_completion.choices[0].message.content


# Sends a POST request to the given URL, using the given list of comments
# (str (URL), List[Comment]) -> Response
def send_request(url, comments):
    addendum = 'entry'

    request_obj = {
        'code': text,
        'comments': json.dumps(
            {
                "comments": comments
            }
        ),
    }

    return requests.post(url + "/" + addendum, params=request_obj)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='FeedBot autograder'
    )

    parser.add_argument('-l', '--local', action='store_true')
    parser.add_argument(
        '-u',
        '--url',
        default='https://feedbot-website-lively-firefly-3841.fly.dev/'
    )

    args = parser.parse_args()

    if args.local:
        with open('test_src.rkt', 'r') as sub:
            text = sub.read()
    else:
        with open('submission/src.rkt', 'r') as sub:
            text = sub.read()

    if args.local:
        with open('key', 'r') as key:
            client = OpenAI(
                api_key=key.read().rstrip()
            )
    else:
        with open('source/key', 'r') as key:
            client = OpenAI(
                api_key=key.read().rstrip()
            )

    answer = get_comment(
        client,
        "Can you point out any flaws in this Racket code?\n\n",
        text
    )

    x = send_request(
        args.url,
        [
            {
                "line_number": 0,
                "text": answer
            }
        ]
    )

    output = {
        "score": 50.0,
        "tests": [
            {
                "output": x.text,
            },
        ],
    }

    if args.local:
        result_path = os.open('.', os.O_RDONLY)
    else:
        result_path = os.open('results', os.O_RDONLY)

    def opener(path, flags):
        return os.open(path, flags, dir_fd=result_path)

    with open('results.json', 'x', opener=opener) as f:
        print(json.dumps(output), file=f)

    os.close(result_path)
